version: '3.3'

services: 
  microservice:
    build: .
    image: cloud-native-go:1.0.1
    environment: 
      - PORT=9090
    ports: 
      - "9090:9090"
  nginx:
    image: "nginx:latest"
    ports: 
      - "8080:80"
    links: 
      - microservice
